# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages
server:
  servlet:
    contextPath: /api

---
# 开发环境配置
spring:
  profiles: dev
logging:
  level:
    com.ykaoqin.kit: DEBUG
data:
  path: d:/env/workspace_idea/nationalholidays/backend/src/main/resources/

---
# 测试环境配置
spring:
  profiles: test
logging:
  level:
    com.ykaoqin.kit: DEBUG
data:
  path: d:/env/workspace_idea/nationalholidays/backend/src/main/resources/

---
# 生产环境配置
spring:
  profiles: prod
logging:
  level:
    com.ykaoqin.kit: INFO
data:
  path: /app/boot/